/* 
 * This file is autogenerated by Grial UIKit build task, please DO NOT modify it
 * manually. Please change colors in the active Theme XAML file and they will be
 * propagated to this file.
 */
using System.Collections.Generic;
using Xamarin.Forms;
using UXDivers.Artina.Shared;

namespace Bullytect.iOS
 {
	internal class ThemeColors : ThemeColorsBase
	{
		private readonly static Dictionary<string, Color> _themeColors = new Dictionary<string, Color>
		{
			{ "AccentColor", Color.FromHex("#6BC7E0") },
			{ "BaseTextColor", Color.FromHex("#666666") },
			{ "InverseTextColor", Color.White },
			{ "BrandColor", Color.FromHex("#6BC7E0") },
			{ "BrandNameColor", Color.FromHex("#FFFFFF") },
			{ "BaseLightTextColor", Color.FromHex("#7b7b7b") },
			{ "OverImageTextColor", Color.FromHex("#FFFFFF") },
			{ "EcommercePromoTextColor", Color.FromHex("#FFFFFF") },
			{ "SocialHeaderTextColor", Color.FromHex("#666666") },
			{ "ArticleHeaderBackgroundColor", Color.FromHex("#F1F3F5") },
			{ "CustomNavBarTextColor", Color.FromHex("#FFFFFF") },
			{ "ListViewItemTextColor", Color.FromHex("#666666") },
			{ "AboutHeaderBackgroundColor", Color.FromHex("#FFFFFF") },
			{ "BasePageColor", Color.FromHex("#FFFFFF") },
			{ "BaseTabbedPageColor", Color.FromHex("#fafafa") },
			{ "MainWrapperBackgroundColor", Color.FromHex("#EFEFEF") },
			{ "CategoriesListIconColor", Color.FromHex("#55000000") },
			{ "DashboardIconColor", Color.FromHex("#FFFFFF") },
			{ "ComplementColor", Color.FromHex("#1c91b1") },
			{ "TranslucidBlack", Color.FromHex("#44000000") },
			{ "TranslucidWhite", Color.FromHex("#22ffffff") },
			{ "OkColor", Color.FromHex("#6bdd9b") },
			{ "ErrorColor", Color.FromHex("#dd6a6b") },
			{ "WarningColor", Color.FromHex("#dbc66e") },
			{ "NotificationColor", Color.FromHex("#6781c0") },
			{ "SaveButtonColor", Color.FromHex("#6bdd9b") },
			{ "DeleteButtonColor", Color.FromHex("#dd6a6b") },
			{ "LabelButtonColor", Color.FromHex("#ffffff") },
			{ "PlaceholderColor", Color.FromHex("#22ffffff") },
			{ "PlaceholderColorEntry", Color.FromHex("#FFFFFF") },
			{ "RoundedLabelBackgroundColor", Color.FromHex("#1c91b1") },
			{ "MainMenuHeaderBackgroundColor", Color.FromHex("#384F63") },
			{ "MainMenuBackgroundColor", Color.FromHex("#F1F3F5") },
			{ "MainMenuSeparatorColor", Color.Transparent },
			{ "MainMenuTextColor", Color.FromHex("#666666") },
			{ "MainMenuIconColor", Color.FromHex("#666666") },
			{ "ListViewSeparatorColor", Color.FromHex("#D3D3D3") },
			{ "BaseSeparatorColor", Color.FromHex("#7b7b7b") },
			{ "ChatRightBalloonBackgroundColor", Color.FromHex("#1c91b1") },
			{ "ChatBalloonFooterTextColor", Color.FromHex("#FFFFFF") },
			{ "ChatRightTextColor", Color.FromHex("#FFFFFF") },
			{ "ChatLeftTextColor", Color.FromHex("#dcc66d") }
		};
		public ThemeColors() : base(_themeColors) {}
	}
}
