//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bullytect.Core.I18N {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Bullytect.Core.I18N.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Page_Common_Title {
            get {
                return ResourceManager.GetString("Page.Common.Title", resourceCulture);
            }
        }
        
        internal static string Page_Settings_Title {
            get {
                return ResourceManager.GetString("Page.Settings.Title", resourceCulture);
            }
        }
        
        internal static string Page_Home_Title {
            get {
                return ResourceManager.GetString("Page.Home.Title", resourceCulture);
            }
        }
        
        internal static string Page_Notifications_Title {
            get {
                return ResourceManager.GetString("Page.Notifications.Title", resourceCulture);
            }
        }
        
        internal static string Page_Children_Title {
            get {
                return ResourceManager.GetString("Page.Children.Title", resourceCulture);
            }
        }
        
        internal static string Page_Profile_Title {
            get {
                return ResourceManager.GetString("Page.Profile.Title", resourceCulture);
            }
        }
        
        internal static string Page_Alerts_Title {
            get {
                return ResourceManager.GetString("Page.Alerts.Title", resourceCulture);
            }
        }
        
        internal static string Page_Alert_Detail_Title {
            get {
                return ResourceManager.GetString("Page.Alert.Detail.Title", resourceCulture);
            }
        }
        
        internal static string Page_Comments_Title {
            get {
                return ResourceManager.GetString("Page.Comments.Title", resourceCulture);
            }
        }
        
        internal static string Page_Comment_Detail_Title {
            get {
                return ResourceManager.GetString("Page.Comment.Detail.Title", resourceCulture);
            }
        }
        
        internal static string Page_Add_Son_Title {
            get {
                return ResourceManager.GetString("Page.Add.Son.Title", resourceCulture);
            }
        }
        
        internal static string Page_Edit_Son_Title {
            get {
                return ResourceManager.GetString("Page.Edit.Son.Title", resourceCulture);
            }
        }
        
        internal static string Page_Son_Profile_Title {
            get {
                return ResourceManager.GetString("Page.Son.Profile.Title", resourceCulture);
            }
        }
        
        internal static string Page_Results_Title {
            get {
                return ResourceManager.GetString("Page.Results.Title", resourceCulture);
            }
        }
        
        internal static string Page_Statistics_Title {
            get {
                return ResourceManager.GetString("Page.Statistics.Title", resourceCulture);
            }
        }
        
        internal static string Common_Title {
            get {
                return ResourceManager.GetString("Common.Title", resourceCulture);
            }
        }
        
        internal static string Common_Loading {
            get {
                return ResourceManager.GetString("Common.Loading", resourceCulture);
            }
        }
        
        internal static string Common_No_Results_Found {
            get {
                return ResourceManager.GetString("Common.No.Results.Found", resourceCulture);
            }
        }
        
        internal static string Common_No_Results_Found_Detail {
            get {
                return ResourceManager.GetString("Common.No.Results.Found.Detail", resourceCulture);
            }
        }
        
        internal static string Common_Timeout_Operation {
            get {
                return ResourceManager.GetString("Common.Timeout.Operation", resourceCulture);
            }
        }
        
        internal static string Common_Invalid_Session {
            get {
                return ResourceManager.GetString("Common.Invalid.Session", resourceCulture);
            }
        }
        
        internal static string Common_Server_Connection_Error {
            get {
                return ResourceManager.GetString("Common.Server.Connection.Error", resourceCulture);
            }
        }
        
        internal static string Common_Server_Error {
            get {
                return ResourceManager.GetString("Common.Server.Error", resourceCulture);
            }
        }
        
        internal static string Common_Cancel_Operation {
            get {
                return ResourceManager.GetString("Common.Cancel.Operation", resourceCulture);
            }
        }
        
        internal static string Common_Cancel_Changes {
            get {
                return ResourceManager.GetString("Common.Cancel.Changes", resourceCulture);
            }
        }
        
        internal static string Common_Retry {
            get {
                return ResourceManager.GetString("Common.Retry", resourceCulture);
            }
        }
        
        internal static string Common_Apply_Filter {
            get {
                return ResourceManager.GetString("Common.Apply.Filter", resourceCulture);
            }
        }
        
        internal static string Common_Btn_Save_Changes {
            get {
                return ResourceManager.GetString("Common.Btn.Save.Changes", resourceCulture);
            }
        }
        
        internal static string Common_RRSS_Facebook {
            get {
                return ResourceManager.GetString("Common.RRSS.Facebook", resourceCulture);
            }
        }
        
        internal static string Common_RRSS_Instagram {
            get {
                return ResourceManager.GetString("Common.RRSS.Instagram", resourceCulture);
            }
        }
        
        internal static string Common_RRSS_Youtube {
            get {
                return ResourceManager.GetString("Common.RRSS.Youtube", resourceCulture);
            }
        }
        
        internal static string Common_Placeholder_Firstname {
            get {
                return ResourceManager.GetString("Common.Placeholder.Firstname", resourceCulture);
            }
        }
        
        internal static string Common_Placeholder_School {
            get {
                return ResourceManager.GetString("Common.Placeholder.School", resourceCulture);
            }
        }
        
        internal static string Common_Placeholder_LastName {
            get {
                return ResourceManager.GetString("Common.Placeholder.LastName", resourceCulture);
            }
        }
        
        internal static string Common_Placeholder_Email {
            get {
                return ResourceManager.GetString("Common.Placeholder.Email", resourceCulture);
            }
        }
        
        internal static string Common_Placeholder_Password {
            get {
                return ResourceManager.GetString("Common.Placeholder.Password", resourceCulture);
            }
        }
        
        internal static string Common_Placeholder_ConfirmPassword {
            get {
                return ResourceManager.GetString("Common.Placeholder.ConfirmPassword", resourceCulture);
            }
        }
        
        internal static string Common_Placeholder_Telephone {
            get {
                return ResourceManager.GetString("Common.Placeholder.Telephone", resourceCulture);
            }
        }
        
        internal static string Common_Placeholder_School_Name {
            get {
                return ResourceManager.GetString("Common.Placeholder.School.Name", resourceCulture);
            }
        }
        
        internal static string Common_Placeholder_School_Residence {
            get {
                return ResourceManager.GetString("Common.Placeholder.School.Residence", resourceCulture);
            }
        }
        
        internal static string Common_Placeholder_School_Province {
            get {
                return ResourceManager.GetString("Common.Placeholder.School.Province", resourceCulture);
            }
        }
        
        internal static string Common_Placeholder_School_Tfno {
            get {
                return ResourceManager.GetString("Common.Placeholder.School.Tfno", resourceCulture);
            }
        }
        
        internal static string Common_Placeholder_School_Email {
            get {
                return ResourceManager.GetString("Common.Placeholder.School.Email", resourceCulture);
            }
        }
        
        internal static string Walkthrough_Btn_Next {
            get {
                return ResourceManager.GetString("Walkthrough.Btn.Next", resourceCulture);
            }
        }
        
        internal static string Walkthrough_Btn_Finish {
            get {
                return ResourceManager.GetString("Walkthrough.Btn.Finish", resourceCulture);
            }
        }
        
        internal static string WelcomePage_MainLabel {
            get {
                return ResourceManager.GetString("WelcomePage.MainLabel", resourceCulture);
            }
        }
        
        internal static string WelcomePage_SecondLabel {
            get {
                return ResourceManager.GetString("WelcomePage.SecondLabel", resourceCulture);
            }
        }
        
        internal static string WelcomePage_ClaimText {
            get {
                return ResourceManager.GetString("WelcomePage.ClaimText", resourceCulture);
            }
        }
        
        internal static string WelcomePage_ClaimTextSecond {
            get {
                return ResourceManager.GetString("WelcomePage.ClaimTextSecond", resourceCulture);
            }
        }
        
        internal static string WelcomePage_Login_Btn {
            get {
                return ResourceManager.GetString("WelcomePage.Login.Btn", resourceCulture);
            }
        }
        
        internal static string WelcomePage_Signup_Btn {
            get {
                return ResourceManager.GetString("WelcomePage.Signup.Btn", resourceCulture);
            }
        }
        
        internal static string WelcomePage_Facebook_Btn {
            get {
                return ResourceManager.GetString("WelcomePage.Facebook.Btn", resourceCulture);
            }
        }
        
        internal static string WelcomePage_Walkthrough_Btn {
            get {
                return ResourceManager.GetString("WelcomePage.Walkthrough.Btn", resourceCulture);
            }
        }
        
        internal static string Login_Text {
            get {
                return ResourceManager.GetString("Login.Text", resourceCulture);
            }
        }
        
        internal static string Login_Authenticating {
            get {
                return ResourceManager.GetString("Login.Authenticating", resourceCulture);
            }
        }
        
        internal static string Login_Success {
            get {
                return ResourceManager.GetString("Login.Success", resourceCulture);
            }
        }
        
        internal static string Login_Failed {
            get {
                return ResourceManager.GetString("Login.Failed", resourceCulture);
            }
        }
        
        internal static string Account_Disabled {
            get {
                return ResourceManager.GetString("Account.Disabled", resourceCulture);
            }
        }
        
        internal static string Account_Locked {
            get {
                return ResourceManager.GetString("Account.Locked", resourceCulture);
            }
        }
        
        internal static string Authentication_Email_Already_Exists {
            get {
                return ResourceManager.GetString("Authentication.Email.Already.Exists", resourceCulture);
            }
        }
        
        internal static string Login_Forget_Password {
            get {
                return ResourceManager.GetString("Login.Forget.Password", resourceCulture);
            }
        }
        
        internal static string Signup_Page_Title {
            get {
                return ResourceManager.GetString("Signup.Page.Title", resourceCulture);
            }
        }
        
        internal static string Signup_Title_Main {
            get {
                return ResourceManager.GetString("Signup.Title.Main", resourceCulture);
            }
        }
        
        internal static string Signup_Title_Second {
            get {
                return ResourceManager.GetString("Signup.Title.Second", resourceCulture);
            }
        }
        
        internal static string Signup_Create {
            get {
                return ResourceManager.GetString("Signup.Create", resourceCulture);
            }
        }
        
        internal static string Signup_Alredy_User {
            get {
                return ResourceManager.GetString("Signup.Alredy.User", resourceCulture);
            }
        }
        
        internal static string Signup_CreatingAccount {
            get {
                return ResourceManager.GetString("Signup.CreatingAccount", resourceCulture);
            }
        }
        
        internal static string Signup_Account_Created {
            get {
                return ResourceManager.GetString("Signup.Account.Created", resourceCulture);
            }
        }
        
        internal static string Signup_Account_Email_Invalid {
            get {
                return ResourceManager.GetString("Signup.Account.Email.Invalid", resourceCulture);
            }
        }
        
        internal static string Signup_Account_Password_Not_Match {
            get {
                return ResourceManager.GetString("Signup.Account.Password.Not.Match", resourceCulture);
            }
        }
        
        internal static string Signup_Cancel {
            get {
                return ResourceManager.GetString("Signup.Cancel", resourceCulture);
            }
        }
        
        internal static string Password_Recovery_Main_Text {
            get {
                return ResourceManager.GetString("Password.Recovery.Main.Text", resourceCulture);
            }
        }
        
        internal static string Password_Recovery_Second_Text {
            get {
                return ResourceManager.GetString("Password.Recovery.Second.Text", resourceCulture);
            }
        }
        
        internal static string Password_Recovery_Send {
            get {
                return ResourceManager.GetString("Password.Recovery.Send", resourceCulture);
            }
        }
        
        internal static string Password_Recovery_Validation_Email {
            get {
                return ResourceManager.GetString("Password.Recovery.Validation.Email", resourceCulture);
            }
        }
        
        internal static string Password_Recovery_Request_Completed {
            get {
                return ResourceManager.GetString("Password.Recovery.Request.Completed", resourceCulture);
            }
        }
        
        internal static string Home_Toolbar_Children {
            get {
                return ResourceManager.GetString("Home.Toolbar.Children", resourceCulture);
            }
        }
        
        internal static string Home_Toolbar_Results {
            get {
                return ResourceManager.GetString("Home.Toolbar.Results", resourceCulture);
            }
        }
        
        internal static string Home_Toolbar_Relations {
            get {
                return ResourceManager.GetString("Home.Toolbar.Relations", resourceCulture);
            }
        }
        
        internal static string Home_Toolbar_Profile {
            get {
                return ResourceManager.GetString("Home.Toolbar.Profile", resourceCulture);
            }
        }
        
        internal static string Home_Loading_Profile {
            get {
                return ResourceManager.GetString("Home.Loading.Profile", resourceCulture);
            }
        }
        
        internal static string Home_Loading_Failed {
            get {
                return ResourceManager.GetString("Home.Loading.Failed", resourceCulture);
            }
        }
        
        internal static string Home_Alerts_List_Title_Filter {
            get {
                return ResourceManager.GetString("Home.Alerts.List.Title.Filter", resourceCulture);
            }
        }
        
        internal static string Home_Alerts_List_Title {
            get {
                return ResourceManager.GetString("Home.Alerts.List.Title", resourceCulture);
            }
        }
        
        internal static string Home_Show_Alerts {
            get {
                return ResourceManager.GetString("Home.Show.Alerts", resourceCulture);
            }
        }
        
        internal static string Home_Alerts_Not_Found_MainText {
            get {
                return ResourceManager.GetString("Home.Alerts.Not.Found.MainText", resourceCulture);
            }
        }
        
        internal static string Home_Alerts_Not_Found_SecondText {
            get {
                return ResourceManager.GetString("Home.Alerts.Not.Found.SecondText", resourceCulture);
            }
        }
        
        internal static string Home_Profile_Load_Error {
            get {
                return ResourceManager.GetString("Home.Profile.Load.Error", resourceCulture);
            }
        }
        
        internal static string Son_Profile_Birthday {
            get {
                return ResourceManager.GetString("Son.Profile.Birthday", resourceCulture);
            }
        }
        
        internal static string Son_Profile_School {
            get {
                return ResourceManager.GetString("Son.Profile.School", resourceCulture);
            }
        }
        
        internal static string Son_Profile_Delete_Confirm {
            get {
                return ResourceManager.GetString("Son.Profile.Delete.Confirm", resourceCulture);
            }
        }
        
        internal static string Children_Not_Found_MainText {
            get {
                return ResourceManager.GetString("Children.Not.Found.MainText", resourceCulture);
            }
        }
        
        internal static string Children_Not_Found_SecondText {
            get {
                return ResourceManager.GetString("Children.Not.Found.SecondText", resourceCulture);
            }
        }
        
        internal static string Children_Error_Ocurred {
            get {
                return ResourceManager.GetString("Children.Error.Ocurred", resourceCulture);
            }
        }
        
        internal static string Children_Toolbar_Results {
            get {
                return ResourceManager.GetString("Children.Toolbar.Results", resourceCulture);
            }
        }
        
        internal static string Children_Toolbar_Alerts {
            get {
                return ResourceManager.GetString("Children.Toolbar.Alerts", resourceCulture);
            }
        }
        
        internal static string Children_Toolbar_Edit {
            get {
                return ResourceManager.GetString("Children.Toolbar.Edit", resourceCulture);
            }
        }
        
        internal static string Children_Toolbar_Relations {
            get {
                return ResourceManager.GetString("Children.Toolbar.Relations", resourceCulture);
            }
        }
        
        internal static string Profile_Save_Changes {
            get {
                return ResourceManager.GetString("Profile.Save.Changes", resourceCulture);
            }
        }
        
        internal static string Profile_Cancel_Changes {
            get {
                return ResourceManager.GetString("Profile.Cancel.Changes", resourceCulture);
            }
        }
        
        internal static string Profile_Saving_Changes {
            get {
                return ResourceManager.GetString("Profile.Saving.Changes", resourceCulture);
            }
        }
        
        internal static string Profile_Delete_Account {
            get {
                return ResourceManager.GetString("Profile.Delete.Account", resourceCulture);
            }
        }
        
        internal static string Profile_Account_Updated {
            get {
                return ResourceManager.GetString("Profile.Account.Updated", resourceCulture);
            }
        }
        
        internal static string Profile_Image_Section {
            get {
                return ResourceManager.GetString("Profile.Image.Section", resourceCulture);
            }
        }
        
        internal static string Profile_General_Information_Section {
            get {
                return ResourceManager.GetString("Profile.General.Information.Section", resourceCulture);
            }
        }
        
        internal static string Profile_Loading_Data {
            get {
                return ResourceManager.GetString("Profile.Loading.Data", resourceCulture);
            }
        }
        
        internal static string Profile_Account_Deleted {
            get {
                return ResourceManager.GetString("Profile.Account.Deleted", resourceCulture);
            }
        }
        
        internal static string Profile_Account_Deleting {
            get {
                return ResourceManager.GetString("Profile.Account.Deleting", resourceCulture);
            }
        }
        
        internal static string Profile_Confirm_Account_Deleting {
            get {
                return ResourceManager.GetString("Profile.Confirm.Account.Deleting", resourceCulture);
            }
        }
        
        internal static string Profile_Confirm_SignOut {
            get {
                return ResourceManager.GetString("Profile.Confirm.SignOut", resourceCulture);
            }
        }
        
        internal static string Profile_Updating_Profile_Image {
            get {
                return ResourceManager.GetString("Profile.Updating.Profile.Image", resourceCulture);
            }
        }
        
        internal static string Profile_Select_Profile_Image {
            get {
                return ResourceManager.GetString("Profile.Select.Profile.Image", resourceCulture);
            }
        }
        
        internal static string Profile_Select_Profile_Image_From_Camera {
            get {
                return ResourceManager.GetString("Profile.Select.Profile.Image.From.Camera", resourceCulture);
            }
        }
        
        internal static string Profile_Select_Profile_Image_From_Galery {
            get {
                return ResourceManager.GetString("Profile.Select.Profile.Image.From.Galery", resourceCulture);
            }
        }
        
        internal static string Profile_Updating_Profile_Image_Failed {
            get {
                return ResourceManager.GetString("Profile.Updating.Profile.Image.Failed", resourceCulture);
            }
        }
        
        internal static string Profile_Updating_Profile_Image_Success {
            get {
                return ResourceManager.GetString("Profile.Updating.Profile.Image.Success", resourceCulture);
            }
        }
        
        internal static string Profile_Updating_Error {
            get {
                return ResourceManager.GetString("Profile.Updating.Error", resourceCulture);
            }
        }
        
        internal static string Profile_Data_Not_Found {
            get {
                return ResourceManager.GetString("Profile.Data.Not.Found", resourceCulture);
            }
        }
        
        internal static string Alerts_Not_Found_MainText {
            get {
                return ResourceManager.GetString("Alerts.Not.Found.MainText", resourceCulture);
            }
        }
        
        internal static string Alerts_Not_Found_SecondText {
            get {
                return ResourceManager.GetString("Alerts.Not.Found.SecondText", resourceCulture);
            }
        }
        
        internal static string Alerts_Delete_Alert {
            get {
                return ResourceManager.GetString("Alerts.Delete.Alert", resourceCulture);
            }
        }
        
        internal static string Alerts_Error_Ocurred {
            get {
                return ResourceManager.GetString("Alerts.Error.Ocurred", resourceCulture);
            }
        }
        
        internal static string Alerts_Confirm_Clear {
            get {
                return ResourceManager.GetString("Alerts.Confirm.Clear", resourceCulture);
            }
        }
        
        internal static string Alert_Confirm_Clear {
            get {
                return ResourceManager.GetString("Alert.Confirm.Clear", resourceCulture);
            }
        }
        
        internal static string Alerts_Deleting_Alerts {
            get {
                return ResourceManager.GetString("Alerts.Deleting.Alerts", resourceCulture);
            }
        }
        
        internal static string Alerts_Warning_Text {
            get {
                return ResourceManager.GetString("Alerts.Warning.Text", resourceCulture);
            }
        }
        
        internal static string Alerts_Danger_Text {
            get {
                return ResourceManager.GetString("Alerts.Danger.Text", resourceCulture);
            }
        }
        
        internal static string Alerts_Info_Text {
            get {
                return ResourceManager.GetString("Alerts.Info.Text", resourceCulture);
            }
        }
        
        internal static string Alerts_Success_Text {
            get {
                return ResourceManager.GetString("Alerts.Success.Text", resourceCulture);
            }
        }
        
        internal static string Alerts_Deleted {
            get {
                return ResourceManager.GetString("Alerts.Deleted", resourceCulture);
            }
        }
        
        internal static string Alerts_Filter_Title {
            get {
                return ResourceManager.GetString("Alerts.Filter.Title", resourceCulture);
            }
        }
        
        internal static string Alerts_Filter_Levels_Title {
            get {
                return ResourceManager.GetString("Alerts.Filter.Levels.Title", resourceCulture);
            }
        }
        
        internal static string Loading_Alerts {
            get {
                return ResourceManager.GetString("Loading.Alerts", resourceCulture);
            }
        }
        
        internal static string EditSon_General_Section_Title {
            get {
                return ResourceManager.GetString("EditSon.General.Section.Title", resourceCulture);
            }
        }
        
        internal static string EditSon_Cancel {
            get {
                return ResourceManager.GetString("EditSon.Cancel", resourceCulture);
            }
        }
        
        internal static string EditSon_General_Change_Profile_Image {
            get {
                return ResourceManager.GetString("EditSon.General.Change.Profile.Image", resourceCulture);
            }
        }
        
        internal static string EditSon_RRSS_Section_Title {
            get {
                return ResourceManager.GetString("EditSon.RRSS.Section.Title", resourceCulture);
            }
        }
        
        internal static string EditSon_Update_Social_Media_Facebook {
            get {
                return ResourceManager.GetString("EditSon.Update.Social.Media.Facebook", resourceCulture);
            }
        }
        
        internal static string EditSon_Update_Social_Media_Instagram {
            get {
                return ResourceManager.GetString("EditSon.Update.Social.Media.Instagram", resourceCulture);
            }
        }
        
        internal static string EditSon_Update_Social_Media_Youtube {
            get {
                return ResourceManager.GetString("EditSon.Update.Social.Media.Youtube", resourceCulture);
            }
        }
        
        internal static string EditSon_Saving_Changes {
            get {
                return ResourceManager.GetString("EditSon.Saving.Changes", resourceCulture);
            }
        }
        
        internal static string EditSon_Saved_Changes_Successfully {
            get {
                return ResourceManager.GetString("EditSon.Saved.Changes.Successfully", resourceCulture);
            }
        }
        
        internal static string EditSon_Social_Media_Added {
            get {
                return ResourceManager.GetString("EditSon.Social.Media.Added", resourceCulture);
            }
        }
        
        internal static string EditSon_Social_Media_Deleted {
            get {
                return ResourceManager.GetString("EditSon.Social.Media.Deleted", resourceCulture);
            }
        }
        
        internal static string EditSon_School_Not_Found {
            get {
                return ResourceManager.GetString("EditSon.School.Not.Found", resourceCulture);
            }
        }
        
        internal static string EditSon_Saving_School {
            get {
                return ResourceManager.GetString("EditSon.Saving.School", resourceCulture);
            }
        }
        
        internal static string EditSon_School_Saved {
            get {
                return ResourceManager.GetString("EditSon.School.Saved", resourceCulture);
            }
        }
        
        internal static string EditSon_Find_School {
            get {
                return ResourceManager.GetString("EditSon.Find.School", resourceCulture);
            }
        }
        
        internal static string EditSon_Find_School_Title {
            get {
                return ResourceManager.GetString("EditSon.Find.School.Title", resourceCulture);
            }
        }
        
        internal static string EditSon_Find_School_Placeholder {
            get {
                return ResourceManager.GetString("EditSon.Find.School.Placeholder", resourceCulture);
            }
        }
        
        internal static string EditSon_Find_School_No_Results_Title {
            get {
                return ResourceManager.GetString("EditSon.Find.School.No.Results.Title", resourceCulture);
            }
        }
        
        internal static string EditSon_Add_School {
            get {
                return ResourceManager.GetString("EditSon.Add.School", resourceCulture);
            }
        }
        
        internal static string EditSon_Find_School_No_Results_Text {
            get {
                return ResourceManager.GetString("EditSon.Find.School.No.Results.Text", resourceCulture);
            }
        }
        
        internal static string EditSon_School_Map_Select {
            get {
                return ResourceManager.GetString("EditSon.School.Map.Select", resourceCulture);
            }
        }
        
        internal static string EditSon_School_Map_Select2 {
            get {
                return ResourceManager.GetString("EditSon.School.Map.Select2", resourceCulture);
            }
        }
        
        internal static string EditSon_School_Map_Visualize {
            get {
                return ResourceManager.GetString("EditSon.School.Map.Visualize", resourceCulture);
            }
        }
        
        internal static string EditSon_School_Map_Visualize2 {
            get {
                return ResourceManager.GetString("EditSon.School.Map.Visualize2", resourceCulture);
            }
        }
        
        internal static string Global_ErrorOcurred {
            get {
                return ResourceManager.GetString("Global.ErrorOcurred", resourceCulture);
            }
        }
        
        internal static string Common_SignOut {
            get {
                return ResourceManager.GetString("Common.SignOut", resourceCulture);
            }
        }
        
        internal static string EditSon_Add_School_Title {
            get {
                return ResourceManager.GetString("EditSon.Add.School.Title", resourceCulture);
            }
        }
        
        internal static string Home_Add_Son {
            get {
                return ResourceManager.GetString("Home.Add.Son", resourceCulture);
            }
        }
        
        internal static string Home_Not_Children_Found {
            get {
                return ResourceManager.GetString("Home.Not.Children.Found", resourceCulture);
            }
        }
        
        internal static string Profile_Can_Not_Take_Photo_From_Camera {
            get {
                return ResourceManager.GetString("Profile.Can.Not.Take.Photo.From.Camera", resourceCulture);
            }
        }
        
        internal static string Profile_Image_Change {
            get {
                return ResourceManager.GetString("Profile.Image.Change", resourceCulture);
            }
        }
        
        internal static string EditSon_Social_Media_Info_Title {
            get {
                return ResourceManager.GetString("EditSon.Social.Media.Info.Title", resourceCulture);
            }
        }
        
        internal static string EditSon_Social_Media_Info_Text {
            get {
                return ResourceManager.GetString("EditSon.Social.Media.Info.Text", resourceCulture);
            }
        }
        
        internal static string EditSon_Social_Media_Invalid_Access_Token {
            get {
                return ResourceManager.GetString("EditSon.Social.Media.Invalid.Access.Token", resourceCulture);
            }
        }
        
        internal static string EditSon_Social_Media_Unconfigured_Access_Token {
            get {
                return ResourceManager.GetString("EditSon.Social.Media.Unconfigured.Access.Token", resourceCulture);
            }
        }
        
        internal static string EditSon_Social_Media_Valid_Access_Token {
            get {
                return ResourceManager.GetString("EditSon.Social.Media.Valid.Access.Token", resourceCulture);
            }
        }
        
        internal static string Settings_Alerts_Categories {
            get {
                return ResourceManager.GetString("Settings.Alerts.Categories", resourceCulture);
            }
        }
        
        internal static string Settings_Alerts_Categories_Success_Alerts_Name {
            get {
                return ResourceManager.GetString("Settings.Alerts.Categories.Success.Alerts.Name", resourceCulture);
            }
        }
        
        internal static string Settings_Alerts_Categories_Success_Alerts_Description {
            get {
                return ResourceManager.GetString("Settings.Alerts.Categories.Success.Alerts.Description", resourceCulture);
            }
        }
        
        internal static string Settings_Alerts_Categories_Info_Alerts_Name {
            get {
                return ResourceManager.GetString("Settings.Alerts.Categories.Info.Alerts.Name", resourceCulture);
            }
        }
        
        internal static string Settings_Alerts_Categories_Info_Alerts_Description {
            get {
                return ResourceManager.GetString("Settings.Alerts.Categories.Info.Alerts.Description", resourceCulture);
            }
        }
        
        internal static string Settings_Alerts_Categories_Warning_Alerts_Name {
            get {
                return ResourceManager.GetString("Settings.Alerts.Categories.Warning.Alerts.Name", resourceCulture);
            }
        }
        
        internal static string Settings_Alerts_Categories_Warning_Alerts_Description {
            get {
                return ResourceManager.GetString("Settings.Alerts.Categories.Warning.Alerts.Description", resourceCulture);
            }
        }
        
        internal static string Settings_Alerts_Categories_Danger_Alerts_Name {
            get {
                return ResourceManager.GetString("Settings.Alerts.Categories.Danger.Alerts.Name", resourceCulture);
            }
        }
        
        internal static string Settings_Alerts_Categories_Danger_Alerts_Description {
            get {
                return ResourceManager.GetString("Settings.Alerts.Categories.Danger.Alerts.Description", resourceCulture);
            }
        }
        
        internal static string Settings_Alerts_General {
            get {
                return ResourceManager.GetString("Settings.Alerts.General", resourceCulture);
            }
        }
        
        internal static string Settings_Antiquity_Of_Alerts {
            get {
                return ResourceManager.GetString("Settings.Antiquity.Of.Alerts", resourceCulture);
            }
        }
        
        internal static string Settings_Antiquity_Of_Alerts_Description {
            get {
                return ResourceManager.GetString("Settings.Antiquity.Of.Alerts.Description", resourceCulture);
            }
        }
        
        internal static string Settings_Antiquity_Of_Alerts_No_Filter {
            get {
                return ResourceManager.GetString("Settings.Antiquity.Of.Alerts.No.Filter", resourceCulture);
            }
        }
        
        internal static string Settings_Push_Notifications {
            get {
                return ResourceManager.GetString("Settings.Push.Notifications", resourceCulture);
            }
        }
        
        internal static string Settings_Push_Notifications_Description {
            get {
                return ResourceManager.GetString("Settings.Push.Notifications.Description", resourceCulture);
            }
        }
        
        internal static string Settings_Remove_Alerts {
            get {
                return ResourceManager.GetString("Settings.Remove.Alerts", resourceCulture);
            }
        }
        
        internal static string Settings_Remove_Alerts_Description {
            get {
                return ResourceManager.GetString("Settings.Remove.Alerts.Description", resourceCulture);
            }
        }
        
        internal static string Settings_Remove_Alerts_Never {
            get {
                return ResourceManager.GetString("Settings.Remove.Alerts.Never", resourceCulture);
            }
        }
        
        internal static string Settings_Remove_Alerts_Last_Hour {
            get {
                return ResourceManager.GetString("Settings.Remove.Alerts.Last.Hour", resourceCulture);
            }
        }
        
        internal static string Settings_Remove_Alerts_Last_Day {
            get {
                return ResourceManager.GetString("Settings.Remove.Alerts.Last.Day", resourceCulture);
            }
        }
        
        internal static string Settings_Remove_Alerts_Last_Month {
            get {
                return ResourceManager.GetString("Settings.Remove.Alerts.Last.Month", resourceCulture);
            }
        }
        
        internal static string Settings_Alerts_Count_New_Alerts {
            get {
                return ResourceManager.GetString("Settings.Alerts.Count.New.Alerts", resourceCulture);
            }
        }
        
        internal static string Settings_Alerts_Count_New_Alerts_Description {
            get {
                return ResourceManager.GetString("Settings.Alerts.Count.New.Alerts.Description", resourceCulture);
            }
        }
        
        internal static string Settings_Alerts_Last_Alerts {
            get {
                return ResourceManager.GetString("Settings.Alerts.Last.Alerts", resourceCulture);
            }
        }
        
        internal static string Settings_Changes_Saved {
            get {
                return ResourceManager.GetString("Settings.Changes.Saved", resourceCulture);
            }
        }
        
        internal static string Results_Comments_Son {
            get {
                return ResourceManager.GetString("Results.Comments.Son", resourceCulture);
            }
        }
        
        internal static string Results_Comments_Son_Loading {
            get {
                return ResourceManager.GetString("Results.Comments.Son.Loading", resourceCulture);
            }
        }
        
        internal static string Results_Comments_Son_Error {
            get {
                return ResourceManager.GetString("Results.Comments.Son.Error", resourceCulture);
            }
        }
        
        internal static string Results_System_Alerts {
            get {
                return ResourceManager.GetString("Results.System.Alerts", resourceCulture);
            }
        }
        
        internal static string Results_System_Alerts_Loading {
            get {
                return ResourceManager.GetString("Results.System.Alerts.Loading", resourceCulture);
            }
        }
        
        internal static string Results_System_Alerts_Error {
            get {
                return ResourceManager.GetString("Results.System.Alerts.Error", resourceCulture);
            }
        }
        
        internal static string Results_Social_Media_Likes {
            get {
                return ResourceManager.GetString("Results.Social.Media.Likes", resourceCulture);
            }
        }
        
        internal static string Results_Social_Media_Likes_Loading {
            get {
                return ResourceManager.GetString("Results.Social.Media.Likes.Loading", resourceCulture);
            }
        }
        
        internal static string Results_Social_Media_Likes_Error {
            get {
                return ResourceManager.GetString("Results.Social.Media.Likes.Error", resourceCulture);
            }
        }
        
        internal static string Results_Most_Active_Friends {
            get {
                return ResourceManager.GetString("Results.Most.Active.Friends", resourceCulture);
            }
        }
        
        internal static string Results_Most_Active_Friends_Loading {
            get {
                return ResourceManager.GetString("Results.Most.Active.Friends.Loading", resourceCulture);
            }
        }
        
        internal static string Results_Most_Active_Friends_Error {
            get {
                return ResourceManager.GetString("Results.Most.Active.Friends.Error", resourceCulture);
            }
        }
        
        internal static string Results_New_Friends {
            get {
                return ResourceManager.GetString("Results.New.Friends", resourceCulture);
            }
        }
        
        internal static string Results_New_Friends_Loading {
            get {
                return ResourceManager.GetString("Results.New.Friends.Loading", resourceCulture);
            }
        }
        
        internal static string Results_New_Friends_Error {
            get {
                return ResourceManager.GetString("Results.New.Friends.Error", resourceCulture);
            }
        }
        
        internal static string Settings_Statistics_Son_General {
            get {
                return ResourceManager.GetString("Settings.Statistics.Son.General", resourceCulture);
            }
        }
        
        internal static string Settings_Statistics_General_Interval {
            get {
                return ResourceManager.GetString("Settings.Statistics.General.Interval", resourceCulture);
            }
        }
        
        internal static string Settings_Statistics_General_Interval_Description {
            get {
                return ResourceManager.GetString("Settings.Statistics.General.Interval.Description", resourceCulture);
            }
        }
        
        internal static string Settings_Statistics_General_Interval_Option {
            get {
                return ResourceManager.GetString("Settings.Statistics.General.Interval.Option", resourceCulture);
            }
        }
        
        internal static string Statistics_Son_Social_Sentiment_Analysis {
            get {
                return ResourceManager.GetString("Statistics.Son.Social.Sentiment.Analysis", resourceCulture);
            }
        }
        
        internal static string Statistics_Son_Social_Sentiment_Analysis_Loading {
            get {
                return ResourceManager.GetString("Statistics.Son.Social.Sentiment.Analysis.Loading", resourceCulture);
            }
        }
        
        internal static string Statistics_Son_Social_Sentiment_Analysis_Error {
            get {
                return ResourceManager.GetString("Statistics.Son.Social.Sentiment.Analysis.Error", resourceCulture);
            }
        }
        
        internal static string Statistics_Son_Social_Media_Activities {
            get {
                return ResourceManager.GetString("Statistics.Son.Social.Media.Activities", resourceCulture);
            }
        }
        
        internal static string Statistics_Son_Social_Media_Activities_Loading {
            get {
                return ResourceManager.GetString("Statistics.Son.Social.Media.Activities.Loading", resourceCulture);
            }
        }
        
        internal static string Statistics_Son_Social_Media_Activities_Error {
            get {
                return ResourceManager.GetString("Statistics.Son.Social.Media.Activities.Error", resourceCulture);
            }
        }
        
        internal static string Statistics_Son_Four_Dimensions {
            get {
                return ResourceManager.GetString("Statistics.Son.Four.Dimensions", resourceCulture);
            }
        }
        
        internal static string Statistics_Son_Four_Dimensions_Loading {
            get {
                return ResourceManager.GetString("Statistics.Son.Four.Dimensions.Loading", resourceCulture);
            }
        }
        
        internal static string Statistics_Son_Four_Dimensions_Error {
            get {
                return ResourceManager.GetString("Statistics.Son.Four.Dimensions.Error", resourceCulture);
            }
        }
        
        internal static string Statistics_Son_Communities {
            get {
                return ResourceManager.GetString("Statistics.Son.Communities", resourceCulture);
            }
        }
        
        internal static string Statistics_Son_Communities_Loading {
            get {
                return ResourceManager.GetString("Statistics.Son.Communities.Loading", resourceCulture);
            }
        }
        
        internal static string Statistics_Son_Communities_Error {
            get {
                return ResourceManager.GetString("Statistics.Son.Communities.Error", resourceCulture);
            }
        }
        
        internal static string Alerts_Category_Default {
            get {
                return ResourceManager.GetString("Alerts.Category.Default", resourceCulture);
            }
        }
        
        internal static string Alerts_Category_Information_Son {
            get {
                return ResourceManager.GetString("Alerts.Category.Information.Son", resourceCulture);
            }
        }
        
        internal static string Alerts_Category_General_Statistics {
            get {
                return ResourceManager.GetString("Alerts.Category.General.Statistics", resourceCulture);
            }
        }
        
        internal static string Alerts_Category_Statistics_Son {
            get {
                return ResourceManager.GetString("Alerts.Category.Statistics.Son", resourceCulture);
            }
        }
        
        internal static string Alerts_Category_Information_Extraction {
            get {
                return ResourceManager.GetString("Alerts.Category.Information.Extraction", resourceCulture);
            }
        }
        
        internal static string Alerts_Category_Information_Son_Action_Text {
            get {
                return ResourceManager.GetString("Alerts.Category.Information.Son.Action.Text", resourceCulture);
            }
        }
        
        internal static string Alerts_Category_General_Statistics_Action_Text {
            get {
                return ResourceManager.GetString("Alerts.Category.General.Statistics.Action.Text", resourceCulture);
            }
        }
        
        internal static string Alerts_Category_Statistics_Son_Action_Text {
            get {
                return ResourceManager.GetString("Alerts.Category.Statistics.Son.Action.Text", resourceCulture);
            }
        }
        
        internal static string Alerts_Category_Information_Extraction_Action_Text {
            get {
                return ResourceManager.GetString("Alerts.Category.Information.Extraction.Action.Text", resourceCulture);
            }
        }
        
        internal static string Comments_Not_Found_MainText {
            get {
                return ResourceManager.GetString("Comments.Not.Found.MainText", resourceCulture);
            }
        }
        
        internal static string Comments_Not_Found_SecondText {
            get {
                return ResourceManager.GetString("Comments.Not.Found.SecondText", resourceCulture);
            }
        }
        
        internal static string Comments_Error_Ocurred {
            get {
                return ResourceManager.GetString("Comments.Error.Ocurred", resourceCulture);
            }
        }
        
        internal static string Comments_Detail_CreatedTime {
            get {
                return ResourceManager.GetString("Comments.Detail.CreatedTime", resourceCulture);
            }
        }
        
        internal static string Comments_Detail_Sentiment_Level_Unknown {
            get {
                return ResourceManager.GetString("Comments.Detail.Sentiment.Level.Unknown", resourceCulture);
            }
        }
        
        internal static string Comments_Detail_Sentiment_Level_Neutro {
            get {
                return ResourceManager.GetString("Comments.Detail.Sentiment.Level.Neutro", resourceCulture);
            }
        }
        
        internal static string Comments_Detail_Sentiment_Level_Positive {
            get {
                return ResourceManager.GetString("Comments.Detail.Sentiment.Level.Positive", resourceCulture);
            }
        }
        
        internal static string Comments_Detail_Sentiment_Level_Negative {
            get {
                return ResourceManager.GetString("Comments.Detail.Sentiment.Level.Negative", resourceCulture);
            }
        }
        
        internal static string Comments_Detail_Adult_Level_Unknown {
            get {
                return ResourceManager.GetString("Comments.Detail.Adult.Level.Unknown", resourceCulture);
            }
        }
        
        internal static string Comments_Detail_Adult_Level_Positive {
            get {
                return ResourceManager.GetString("Comments.Detail.Adult.Level.Positive", resourceCulture);
            }
        }
        
        internal static string Comments_Detail_Adult_Level_Negative {
            get {
                return ResourceManager.GetString("Comments.Detail.Adult.Level.Negative", resourceCulture);
            }
        }
        
        internal static string Comments_Detail_Drugs_Level_Unknown {
            get {
                return ResourceManager.GetString("Comments.Detail.Drugs.Level.Unknown", resourceCulture);
            }
        }
        
        internal static string Comments_Detail_Drugs_Level_Positive {
            get {
                return ResourceManager.GetString("Comments.Detail.Drugs.Level.Positive", resourceCulture);
            }
        }
        
        internal static string Comments_Detail_Drugs_Level_Negative {
            get {
                return ResourceManager.GetString("Comments.Detail.Drugs.Level.Negative", resourceCulture);
            }
        }
        
        internal static string Comments_Detail_Violence_Level_Unknown {
            get {
                return ResourceManager.GetString("Comments.Detail.Violence.Level.Unknown", resourceCulture);
            }
        }
        
        internal static string Comments_Detail_Violence_Level_Positive {
            get {
                return ResourceManager.GetString("Comments.Detail.Violence.Level.Positive", resourceCulture);
            }
        }
        
        internal static string Comments_Detail_Violence_Level_Negative {
            get {
                return ResourceManager.GetString("Comments.Detail.Violence.Level.Negative", resourceCulture);
            }
        }
        
        internal static string Comments_Detail_Bullying_Level_Unknown {
            get {
                return ResourceManager.GetString("Comments.Detail.Bullying.Level.Unknown", resourceCulture);
            }
        }
        
        internal static string Comments_Detail_Bullying_Level_Positive {
            get {
                return ResourceManager.GetString("Comments.Detail.Bullying.Level.Positive", resourceCulture);
            }
        }
        
        internal static string Comments_Detail_Bullying_Level_Negative {
            get {
                return ResourceManager.GetString("Comments.Detail.Bullying.Level.Negative", resourceCulture);
            }
        }
        
        internal static string Comments_Dimensions_Filter {
            get {
                return ResourceManager.GetString("Comments.Dimensions.Filter", resourceCulture);
            }
        }
        
        internal static string Comments_Dimensions_Filter_All {
            get {
                return ResourceManager.GetString("Comments.Dimensions.Filter.All", resourceCulture);
            }
        }
        
        internal static string Comments_Dimensions_Filter_All_Description {
            get {
                return ResourceManager.GetString("Comments.Dimensions.Filter.All.Description", resourceCulture);
            }
        }
        
        internal static string Comments_Dimensions_Violence {
            get {
                return ResourceManager.GetString("Comments.Dimensions.Violence", resourceCulture);
            }
        }
        
        internal static string Comments_Dimensions_Violence_Description {
            get {
                return ResourceManager.GetString("Comments.Dimensions.Violence.Description", resourceCulture);
            }
        }
        
        internal static string Comments_Dimensions_Drugs {
            get {
                return ResourceManager.GetString("Comments.Dimensions.Drugs", resourceCulture);
            }
        }
        
        internal static string Comments_Dimensions_Drugs_Description {
            get {
                return ResourceManager.GetString("Comments.Dimensions.Drugs.Description", resourceCulture);
            }
        }
        
        internal static string Comments_Dimensions_Bullying {
            get {
                return ResourceManager.GetString("Comments.Dimensions.Bullying", resourceCulture);
            }
        }
        
        internal static string Comments_Dimensions_Bullying_Description {
            get {
                return ResourceManager.GetString("Comments.Dimensions.Bullying.Description", resourceCulture);
            }
        }
        
        internal static string Comments_Dimensions_Sex {
            get {
                return ResourceManager.GetString("Comments.Dimensions.Sex", resourceCulture);
            }
        }
        
        internal static string Comments_Dimensions_Sex_Description {
            get {
                return ResourceManager.GetString("Comments.Dimensions.Sex.Description", resourceCulture);
            }
        }
        
        internal static string Comments_Dimensions_Filter_Title {
            get {
                return ResourceManager.GetString("Comments.Dimensions.Filter.Title", resourceCulture);
            }
        }
        
        internal static string Comments_SocialMedia_Filter_All {
            get {
                return ResourceManager.GetString("Comments.SocialMedia.Filter.All", resourceCulture);
            }
        }
        
        internal static string Comments_SocialMedia_Filter_All_Description {
            get {
                return ResourceManager.GetString("Comments.SocialMedia.Filter.All.Description", resourceCulture);
            }
        }
    }
}
