//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bullytect.Core.I18N {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Bullytect.Core.I18N.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Page_Common_Title {
            get {
                return ResourceManager.GetString("Page.Common.Title", resourceCulture);
            }
        }
        
        internal static string Page_Notifications_Title {
            get {
                return ResourceManager.GetString("Page.Notifications.Title", resourceCulture);
            }
        }
        
        internal static string Page_Children_Title {
            get {
                return ResourceManager.GetString("Page.Children.Title", resourceCulture);
            }
        }
        
        internal static string Page_Edit_Profile_Title {
            get {
                return ResourceManager.GetString("Page.Edit.Profile.Title", resourceCulture);
            }
        }
        
        internal static string Common_Loading {
            get {
                return ResourceManager.GetString("Common.Loading", resourceCulture);
            }
        }
        
        internal static string Common_Timeout_Operation {
            get {
                return ResourceManager.GetString("Common.Timeout.Operation", resourceCulture);
            }
        }
        
        internal static string Common_Server_Connection_Error {
            get {
                return ResourceManager.GetString("Common.Server.Connection.Error", resourceCulture);
            }
        }
        
        internal static string Walkthrough_Btn_Next {
            get {
                return ResourceManager.GetString("Walkthrough.Btn.Next", resourceCulture);
            }
        }
        
        internal static string Walkthrough_Btn_Finish {
            get {
                return ResourceManager.GetString("Walkthrough.Btn.Finish", resourceCulture);
            }
        }
        
        internal static string WelcomePage_MainLabel {
            get {
                return ResourceManager.GetString("WelcomePage.MainLabel", resourceCulture);
            }
        }
        
        internal static string WelcomePage_SecondLabel {
            get {
                return ResourceManager.GetString("WelcomePage.SecondLabel", resourceCulture);
            }
        }
        
        internal static string WelcomePage_ClaimText {
            get {
                return ResourceManager.GetString("WelcomePage.ClaimText", resourceCulture);
            }
        }
        
        internal static string WelcomePage_ClaimTextSecond {
            get {
                return ResourceManager.GetString("WelcomePage.ClaimTextSecond", resourceCulture);
            }
        }
        
        internal static string WelcomePage_Login_Btn {
            get {
                return ResourceManager.GetString("WelcomePage.Login.Btn", resourceCulture);
            }
        }
        
        internal static string WelcomePage_Signup_Btn {
            get {
                return ResourceManager.GetString("WelcomePage.Signup.Btn", resourceCulture);
            }
        }
        
        internal static string WelcomePage_Facebook_Btn {
            get {
                return ResourceManager.GetString("WelcomePage.Facebook.Btn", resourceCulture);
            }
        }
        
        internal static string WelcomePage_Walkthrough_Btn {
            get {
                return ResourceManager.GetString("WelcomePage.Walkthrough.Btn", resourceCulture);
            }
        }
        
        internal static string Login_Text {
            get {
                return ResourceManager.GetString("Login.Text", resourceCulture);
            }
        }
        
        internal static string Login_Authenticating {
            get {
                return ResourceManager.GetString("Login.Authenticating", resourceCulture);
            }
        }
        
        internal static string Login_Success {
            get {
                return ResourceManager.GetString("Login.Success", resourceCulture);
            }
        }
        
        internal static string Login_Failed {
            get {
                return ResourceManager.GetString("Login.Failed", resourceCulture);
            }
        }
        
        internal static string Login_Forget_Password {
            get {
                return ResourceManager.GetString("Login.Forget.Password", resourceCulture);
            }
        }
        
        internal static string Signup_Page_Title {
            get {
                return ResourceManager.GetString("Signup.Page.Title", resourceCulture);
            }
        }
        
        internal static string Signup_Title_Main {
            get {
                return ResourceManager.GetString("Signup.Title.Main", resourceCulture);
            }
        }
        
        internal static string Signup_Title_Second {
            get {
                return ResourceManager.GetString("Signup.Title.Second", resourceCulture);
            }
        }
        
        internal static string Signup_Create {
            get {
                return ResourceManager.GetString("Signup.Create", resourceCulture);
            }
        }
        
        internal static string Signup_Alredy_User {
            get {
                return ResourceManager.GetString("Signup.Alredy.User", resourceCulture);
            }
        }
        
        internal static string Signup_CreatingAccount {
            get {
                return ResourceManager.GetString("Signup.CreatingAccount", resourceCulture);
            }
        }
        
        internal static string Signup_Account_Created {
            get {
                return ResourceManager.GetString("Signup.Account.Created", resourceCulture);
            }
        }
        
        internal static string Signup_Account_Firstname_Placeholder {
            get {
                return ResourceManager.GetString("Signup.Account.Firstname.Placeholder", resourceCulture);
            }
        }
        
        internal static string Signup_Account_LastName_Placeholder {
            get {
                return ResourceManager.GetString("Signup.Account.LastName.Placeholder", resourceCulture);
            }
        }
        
        internal static string Signup_Account_Email_Placeholder {
            get {
                return ResourceManager.GetString("Signup.Account.Email.Placeholder", resourceCulture);
            }
        }
        
        internal static string Signup_Account_Password_Placeholder {
            get {
                return ResourceManager.GetString("Signup.Account.Password.Placeholder", resourceCulture);
            }
        }
        
        internal static string Signup_Account_ConfirmPassword_Placeholder {
            get {
                return ResourceManager.GetString("Signup.Account.ConfirmPassword.Placeholder", resourceCulture);
            }
        }
        
        internal static string Signup_Account_Telephone_Placeholder {
            get {
                return ResourceManager.GetString("Signup.Account.Telephone.Placeholder", resourceCulture);
            }
        }
        
        internal static string Signup_Account_Email_Invalid {
            get {
                return ResourceManager.GetString("Signup.Account.Email.Invalid", resourceCulture);
            }
        }
        
        internal static string Signup_Account_Password_Not_Match {
            get {
                return ResourceManager.GetString("Signup.Account.Password.Not.Match", resourceCulture);
            }
        }
        
        internal static string Password_Recovery_Main_Text {
            get {
                return ResourceManager.GetString("Password.Recovery.Main.Text", resourceCulture);
            }
        }
        
        internal static string Password_Recovery_Second_Text {
            get {
                return ResourceManager.GetString("Password.Recovery.Second.Text", resourceCulture);
            }
        }
        
        internal static string Password_Recovery_Send {
            get {
                return ResourceManager.GetString("Password.Recovery.Send", resourceCulture);
            }
        }
        
        internal static string Password_Recovery_Validation_Email {
            get {
                return ResourceManager.GetString("Password.Recovery.Validation.Email", resourceCulture);
            }
        }
        
        internal static string Password_Recovery_Request_Completed {
            get {
                return ResourceManager.GetString("Password.Recovery.Request.Completed", resourceCulture);
            }
        }
        
        internal static string Profile_Toolbar_Children {
            get {
                return ResourceManager.GetString("Profile.Toolbar.Children", resourceCulture);
            }
        }
        
        internal static string Profile_Toolbar_Notifications {
            get {
                return ResourceManager.GetString("Profile.Toolbar.Notifications", resourceCulture);
            }
        }
        
        internal static string Profile_Loading_Failed {
            get {
                return ResourceManager.GetString("Profile.Loading.Failed", resourceCulture);
            }
        }
        
        internal static string Profile_Children_List_Title {
            get {
                return ResourceManager.GetString("Profile.Children.List.Title", resourceCulture);
            }
        }
        
        internal static string Son_Profile_Birthday {
            get {
                return ResourceManager.GetString("Son.Profile.Birthday", resourceCulture);
            }
        }
        
        internal static string Son_Profile_School {
            get {
                return ResourceManager.GetString("Son.Profile.School", resourceCulture);
            }
        }
        
        internal static string Children_Not_Found_MainText {
            get {
                return ResourceManager.GetString("Children.Not.Found.MainText", resourceCulture);
            }
        }
        
        internal static string Children_Not_Found_SecondText {
            get {
                return ResourceManager.GetString("Children.Not.Found.SecondText", resourceCulture);
            }
        }
        
        internal static string Children_Error_Ocurred {
            get {
                return ResourceManager.GetString("Children.Error.Ocurred", resourceCulture);
            }
        }
        
        internal static string Global_ErrorOcurred {
            get {
                return ResourceManager.GetString("Global.ErrorOcurred", resourceCulture);
            }
        }
    }
}
