//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bullytect.Core.I18N {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Bullytect.Core.I18N.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Page_Common_Title {
            get {
                return ResourceManager.GetString("Page.Common.Title", resourceCulture);
            }
        }
        
        internal static string Page_Home_Title {
            get {
                return ResourceManager.GetString("Page.Home.Title", resourceCulture);
            }
        }
        
        internal static string Page_Notifications_Title {
            get {
                return ResourceManager.GetString("Page.Notifications.Title", resourceCulture);
            }
        }
        
        internal static string Page_Children_Title {
            get {
                return ResourceManager.GetString("Page.Children.Title", resourceCulture);
            }
        }
        
        internal static string Page_Profile_Title {
            get {
                return ResourceManager.GetString("Page.Profile.Title", resourceCulture);
            }
        }
        
        internal static string Page_Alerts_Title {
            get {
                return ResourceManager.GetString("Page.Alerts.Title", resourceCulture);
            }
        }
        
        internal static string Page_Alert_Detail_Title {
            get {
                return ResourceManager.GetString("Page.Alert.Detail.Title", resourceCulture);
            }
        }
        
        internal static string Page_Add_Son_Title {
            get {
                return ResourceManager.GetString("Page.Add.Son.Title", resourceCulture);
            }
        }
        
        internal static string Page_Edit_Son_Title {
            get {
                return ResourceManager.GetString("Page.Edit.Son.Title", resourceCulture);
            }
        }
        
        internal static string Common_Loading {
            get {
                return ResourceManager.GetString("Common.Loading", resourceCulture);
            }
        }
        
        internal static string Common_Timeout_Operation {
            get {
                return ResourceManager.GetString("Common.Timeout.Operation", resourceCulture);
            }
        }
        
        internal static string Common_Invalid_Session {
            get {
                return ResourceManager.GetString("Common.Invalid.Session", resourceCulture);
            }
        }
        
        internal static string Common_Server_Connection_Error {
            get {
                return ResourceManager.GetString("Common.Server.Connection.Error", resourceCulture);
            }
        }
        
        internal static string Common_Server_Error {
            get {
                return ResourceManager.GetString("Common.Server.Error", resourceCulture);
            }
        }
        
        internal static string Common_Cancel_Operation {
            get {
                return ResourceManager.GetString("Common.Cancel.Operation", resourceCulture);
            }
        }
        
        internal static string Common_Btn_Save_Changes {
            get {
                return ResourceManager.GetString("Common.Btn.Save.Changes", resourceCulture);
            }
        }
        
        internal static string Common_RRSS_Facebook {
            get {
                return ResourceManager.GetString("Common.RRSS.Facebook", resourceCulture);
            }
        }
        
        internal static string Common_RRSS_Instagram {
            get {
                return ResourceManager.GetString("Common.RRSS.Instagram", resourceCulture);
            }
        }
        
        internal static string Common_RRSS_Youtube {
            get {
                return ResourceManager.GetString("Common.RRSS.Youtube", resourceCulture);
            }
        }
        
        internal static string Common_Placeholder_Firstname {
            get {
                return ResourceManager.GetString("Common.Placeholder.Firstname", resourceCulture);
            }
        }
        
        internal static string Common_Placeholder_LastName {
            get {
                return ResourceManager.GetString("Common.Placeholder.LastName", resourceCulture);
            }
        }
        
        internal static string Common_Placeholder_Email {
            get {
                return ResourceManager.GetString("Common.Placeholder.Email", resourceCulture);
            }
        }
        
        internal static string Common_Placeholder_Password {
            get {
                return ResourceManager.GetString("Common.Placeholder.Password", resourceCulture);
            }
        }
        
        internal static string Common_Placeholder_ConfirmPassword {
            get {
                return ResourceManager.GetString("Common.Placeholder.ConfirmPassword", resourceCulture);
            }
        }
        
        internal static string Common_Placeholder_Telephone {
            get {
                return ResourceManager.GetString("Common.Placeholder.Telephone", resourceCulture);
            }
        }
        
        internal static string Common_Placeholder_School_Name {
            get {
                return ResourceManager.GetString("Common.Placeholder.School.Name", resourceCulture);
            }
        }
        
        internal static string Common_Placeholder_School_Residence {
            get {
                return ResourceManager.GetString("Common.Placeholder.School.Residence", resourceCulture);
            }
        }
        
        internal static string Common_Placeholder_School_Location {
            get {
                return ResourceManager.GetString("Common.Placeholder.School.Location", resourceCulture);
            }
        }
        
        internal static string Common_Placeholder_School_Province {
            get {
                return ResourceManager.GetString("Common.Placeholder.School.Province", resourceCulture);
            }
        }
        
        internal static string Common_Placeholder_School_Tfno {
            get {
                return ResourceManager.GetString("Common.Placeholder.School.Tfno", resourceCulture);
            }
        }
        
        internal static string Common_Placeholder_School_Email {
            get {
                return ResourceManager.GetString("Common.Placeholder.School.Email", resourceCulture);
            }
        }
        
        internal static string Walkthrough_Btn_Next {
            get {
                return ResourceManager.GetString("Walkthrough.Btn.Next", resourceCulture);
            }
        }
        
        internal static string Walkthrough_Btn_Finish {
            get {
                return ResourceManager.GetString("Walkthrough.Btn.Finish", resourceCulture);
            }
        }
        
        internal static string WelcomePage_MainLabel {
            get {
                return ResourceManager.GetString("WelcomePage.MainLabel", resourceCulture);
            }
        }
        
        internal static string WelcomePage_SecondLabel {
            get {
                return ResourceManager.GetString("WelcomePage.SecondLabel", resourceCulture);
            }
        }
        
        internal static string WelcomePage_ClaimText {
            get {
                return ResourceManager.GetString("WelcomePage.ClaimText", resourceCulture);
            }
        }
        
        internal static string WelcomePage_ClaimTextSecond {
            get {
                return ResourceManager.GetString("WelcomePage.ClaimTextSecond", resourceCulture);
            }
        }
        
        internal static string WelcomePage_Login_Btn {
            get {
                return ResourceManager.GetString("WelcomePage.Login.Btn", resourceCulture);
            }
        }
        
        internal static string WelcomePage_Signup_Btn {
            get {
                return ResourceManager.GetString("WelcomePage.Signup.Btn", resourceCulture);
            }
        }
        
        internal static string WelcomePage_Facebook_Btn {
            get {
                return ResourceManager.GetString("WelcomePage.Facebook.Btn", resourceCulture);
            }
        }
        
        internal static string WelcomePage_Walkthrough_Btn {
            get {
                return ResourceManager.GetString("WelcomePage.Walkthrough.Btn", resourceCulture);
            }
        }
        
        internal static string Login_Text {
            get {
                return ResourceManager.GetString("Login.Text", resourceCulture);
            }
        }
        
        internal static string Login_Authenticating {
            get {
                return ResourceManager.GetString("Login.Authenticating", resourceCulture);
            }
        }
        
        internal static string Login_Success {
            get {
                return ResourceManager.GetString("Login.Success", resourceCulture);
            }
        }
        
        internal static string Login_Failed {
            get {
                return ResourceManager.GetString("Login.Failed", resourceCulture);
            }
        }
        
        internal static string Login_Forget_Password {
            get {
                return ResourceManager.GetString("Login.Forget.Password", resourceCulture);
            }
        }
        
        internal static string Signup_Page_Title {
            get {
                return ResourceManager.GetString("Signup.Page.Title", resourceCulture);
            }
        }
        
        internal static string Signup_Title_Main {
            get {
                return ResourceManager.GetString("Signup.Title.Main", resourceCulture);
            }
        }
        
        internal static string Signup_Title_Second {
            get {
                return ResourceManager.GetString("Signup.Title.Second", resourceCulture);
            }
        }
        
        internal static string Signup_Create {
            get {
                return ResourceManager.GetString("Signup.Create", resourceCulture);
            }
        }
        
        internal static string Signup_Alredy_User {
            get {
                return ResourceManager.GetString("Signup.Alredy.User", resourceCulture);
            }
        }
        
        internal static string Signup_CreatingAccount {
            get {
                return ResourceManager.GetString("Signup.CreatingAccount", resourceCulture);
            }
        }
        
        internal static string Signup_Account_Created {
            get {
                return ResourceManager.GetString("Signup.Account.Created", resourceCulture);
            }
        }
        
        internal static string Signup_Account_Email_Invalid {
            get {
                return ResourceManager.GetString("Signup.Account.Email.Invalid", resourceCulture);
            }
        }
        
        internal static string Signup_Account_Password_Not_Match {
            get {
                return ResourceManager.GetString("Signup.Account.Password.Not.Match", resourceCulture);
            }
        }
        
        internal static string Password_Recovery_Main_Text {
            get {
                return ResourceManager.GetString("Password.Recovery.Main.Text", resourceCulture);
            }
        }
        
        internal static string Password_Recovery_Second_Text {
            get {
                return ResourceManager.GetString("Password.Recovery.Second.Text", resourceCulture);
            }
        }
        
        internal static string Password_Recovery_Send {
            get {
                return ResourceManager.GetString("Password.Recovery.Send", resourceCulture);
            }
        }
        
        internal static string Password_Recovery_Validation_Email {
            get {
                return ResourceManager.GetString("Password.Recovery.Validation.Email", resourceCulture);
            }
        }
        
        internal static string Password_Recovery_Request_Completed {
            get {
                return ResourceManager.GetString("Password.Recovery.Request.Completed", resourceCulture);
            }
        }
        
        internal static string Home_Toolbar_Children {
            get {
                return ResourceManager.GetString("Home.Toolbar.Children", resourceCulture);
            }
        }
        
        internal static string Home_Toolbar_Profile {
            get {
                return ResourceManager.GetString("Home.Toolbar.Profile", resourceCulture);
            }
        }
        
        internal static string Home_Loading_Profile {
            get {
                return ResourceManager.GetString("Home.Loading.Profile", resourceCulture);
            }
        }
        
        internal static string Home_Loading_Failed {
            get {
                return ResourceManager.GetString("Home.Loading.Failed", resourceCulture);
            }
        }
        
        internal static string Home_Children_List_Title {
            get {
                return ResourceManager.GetString("Home.Children.List.Title", resourceCulture);
            }
        }
        
        internal static string Home_Profile_Load_Error {
            get {
                return ResourceManager.GetString("Home.Profile.Load.Error", resourceCulture);
            }
        }
        
        internal static string Son_Profile_Birthday {
            get {
                return ResourceManager.GetString("Son.Profile.Birthday", resourceCulture);
            }
        }
        
        internal static string Son_Profile_School {
            get {
                return ResourceManager.GetString("Son.Profile.School", resourceCulture);
            }
        }
        
        internal static string Children_Not_Found_MainText {
            get {
                return ResourceManager.GetString("Children.Not.Found.MainText", resourceCulture);
            }
        }
        
        internal static string Children_Not_Found_SecondText {
            get {
                return ResourceManager.GetString("Children.Not.Found.SecondText", resourceCulture);
            }
        }
        
        internal static string Children_Error_Ocurred {
            get {
                return ResourceManager.GetString("Children.Error.Ocurred", resourceCulture);
            }
        }
        
        internal static string Children_Toolbar_Profile {
            get {
                return ResourceManager.GetString("Children.Toolbar.Profile", resourceCulture);
            }
        }
        
        internal static string Children_Toolbar_Alerts {
            get {
                return ResourceManager.GetString("Children.Toolbar.Alerts", resourceCulture);
            }
        }
        
        internal static string Children_Toolbar_Edit {
            get {
                return ResourceManager.GetString("Children.Toolbar.Edit", resourceCulture);
            }
        }
        
        internal static string Profile_Save_Changes {
            get {
                return ResourceManager.GetString("Profile.Save.Changes", resourceCulture);
            }
        }
        
        internal static string Profile_Saving_Changes {
            get {
                return ResourceManager.GetString("Profile.Saving.Changes", resourceCulture);
            }
        }
        
        internal static string Profile_Delete_Account {
            get {
                return ResourceManager.GetString("Profile.Delete.Account", resourceCulture);
            }
        }
        
        internal static string Profile_Account_Updated {
            get {
                return ResourceManager.GetString("Profile.Account.Updated", resourceCulture);
            }
        }
        
        internal static string Profile_Image_Section {
            get {
                return ResourceManager.GetString("Profile.Image.Section", resourceCulture);
            }
        }
        
        internal static string Profile_General_Information_Section {
            get {
                return ResourceManager.GetString("Profile.General.Information.Section", resourceCulture);
            }
        }
        
        internal static string Profile_Loading_Data {
            get {
                return ResourceManager.GetString("Profile.Loading.Data", resourceCulture);
            }
        }
        
        internal static string Profile_Account_Deleted {
            get {
                return ResourceManager.GetString("Profile.Account.Deleted", resourceCulture);
            }
        }
        
        internal static string Profile_Account_Deleting {
            get {
                return ResourceManager.GetString("Profile.Account.Deleting", resourceCulture);
            }
        }
        
        internal static string Profile_Confirm_Account_Deleting {
            get {
                return ResourceManager.GetString("Profile.Confirm.Account.Deleting", resourceCulture);
            }
        }
        
        internal static string Profile_Confirm_SignOut {
            get {
                return ResourceManager.GetString("Profile.Confirm.SignOut", resourceCulture);
            }
        }
        
        internal static string Profile_Updating_Profile_Image {
            get {
                return ResourceManager.GetString("Profile.Updating.Profile.Image", resourceCulture);
            }
        }
        
        internal static string Profile_Select_Profile_Image {
            get {
                return ResourceManager.GetString("Profile.Select.Profile.Image", resourceCulture);
            }
        }
        
        internal static string Profile_Select_Profile_Image_From_Camera {
            get {
                return ResourceManager.GetString("Profile.Select.Profile.Image.From.Camera", resourceCulture);
            }
        }
        
        internal static string Profile_Select_Profile_Image_From_Galery {
            get {
                return ResourceManager.GetString("Profile.Select.Profile.Image.From.Galery", resourceCulture);
            }
        }
        
        internal static string Profile_Updating_Profile_Image_Failed {
            get {
                return ResourceManager.GetString("Profile.Updating.Profile.Image.Failed", resourceCulture);
            }
        }
        
        internal static string Profile_Updating_Profile_Image_Success {
            get {
                return ResourceManager.GetString("Profile.Updating.Profile.Image.Success", resourceCulture);
            }
        }
        
        internal static string Notification_Not_Found_MainText {
            get {
                return ResourceManager.GetString("Notification.Not.Found.MainText", resourceCulture);
            }
        }
        
        internal static string Notification_Error_Ocurred {
            get {
                return ResourceManager.GetString("Notification.Error.Ocurred", resourceCulture);
            }
        }
        
        internal static string Loading_Alerts {
            get {
                return ResourceManager.GetString("Loading.Alerts", resourceCulture);
            }
        }
        
        internal static string EditSon_General_Section_Title {
            get {
                return ResourceManager.GetString("EditSon.General.Section.Title", resourceCulture);
            }
        }
        
        internal static string EditSon_General_Change_Profile_Image {
            get {
                return ResourceManager.GetString("EditSon.General.Change.Profile.Image", resourceCulture);
            }
        }
        
        internal static string EditSon_RRSS_Section_Title {
            get {
                return ResourceManager.GetString("EditSon.RRSS.Section.Title", resourceCulture);
            }
        }
        
        internal static string EditSon_Update_Social_Media_Facebook {
            get {
                return ResourceManager.GetString("EditSon.Update.Social.Media.Facebook", resourceCulture);
            }
        }
        
        internal static string EditSon_Update_Social_Media_Instagram {
            get {
                return ResourceManager.GetString("EditSon.Update.Social.Media.Instagram", resourceCulture);
            }
        }
        
        internal static string EditSon_Update_Social_Media_Youtube {
            get {
                return ResourceManager.GetString("EditSon.Update.Social.Media.Youtube", resourceCulture);
            }
        }
        
        internal static string EditSon_Saving_Changes {
            get {
                return ResourceManager.GetString("EditSon.Saving.Changes", resourceCulture);
            }
        }
        
        internal static string EditSon_Saved_Changes_Successfully {
            get {
                return ResourceManager.GetString("EditSon.Saved.Changes.Successfully", resourceCulture);
            }
        }
        
        internal static string EditSon_Social_Media_Added {
            get {
                return ResourceManager.GetString("EditSon.Social.Media.Added", resourceCulture);
            }
        }
        
        internal static string EditSon_Social_Media_Deleted {
            get {
                return ResourceManager.GetString("EditSon.Social.Media.Deleted", resourceCulture);
            }
        }
        
        internal static string EditSon_School_Not_Found {
            get {
                return ResourceManager.GetString("EditSon.School.Not.Found", resourceCulture);
            }
        }
        
        internal static string EditSon_Saving_School {
            get {
                return ResourceManager.GetString("EditSon.Saving.School", resourceCulture);
            }
        }
        
        internal static string EditSon_School_Saved {
            get {
                return ResourceManager.GetString("EditSon.School.Saved", resourceCulture);
            }
        }
        
        internal static string Global_ErrorOcurred {
            get {
                return ResourceManager.GetString("Global.ErrorOcurred", resourceCulture);
            }
        }
    }
}
